# Generated by Django 3.2 on 2021-04-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_email_user_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.IntegerField(),
        ),
    ]
