# Generated by Django 3.2 on 2021-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20210419_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weather_pass',
            field=models.BooleanField(default=False),
        ),
    ]
